# shellcheck shell=bash
# Rulings ledger: the commander's lasting preferences, append-only, latest wins per topic.
#
#   $CHARTROOM_HOME/rulings.log, one ruling per line, never edited:
#     <ts> [r-xxxx] topic=<slug> supersedes=<r-id|-> src=<token> :: <text>
#
# A topic is the unit of "latest wins": the newest ruling in a topic is live unless a later
# ruling names it in supersedes= (which retires it across topics too). A ruling whose text
# starts with "(retired)" ends its topic. The live set is rendered into a generated block in
# the preferences file (commander.md, or a legacy captain.md) between RULES_BEGIN/RULES_END;
# text outside the block stays hand-written.

RULES_BEGIN='<!-- chartroom:rulings (generated by `chartroom rule`; change with `chartroom rule add`, never by hand) -->'
RULES_END='<!-- /chartroom:rulings -->'

rules_file() { printf '%s/rulings.log' "$CR_HOME"; }

# The standing-preferences file: commander.md, else a legacy captain.md, else commander.md.
prefs_file() {
  if [[ -f "$CR_HOME/commander.md" ]]; then printf '%s/commander.md' "$CR_HOME"
  elif [[ -f "$CR_HOME/captain.md" ]]; then printf '%s/captain.md' "$CR_HOME"
  else printf '%s/commander.md' "$CR_HOME"; fi
}

# Every ruling as a JSON array, in file order. Malformed lines fail loudly with their number.
rules_json() {
  local f; f="$(rules_file)"
  [[ -s "$f" ]] || { echo '[]'; return 0; }
  jq -R -s -c '
    split("\n") | to_entries | map(select(.value != "")) | map(
      .key as $n | .value
      | capture("^(?<ts>[0-9T:Z-]+) \\[(?<id>r-[0-9a-f]{4,})\\] topic=(?<topic>[a-z0-9][a-z0-9-]*) supersedes=(?<supersedes>r-[0-9a-f]{4,}|-) src=(?<src>[^ ]+) :: (?<text>.*)$")
        // error("rulings.log line \($n + 1) is malformed: \(.)")
      | . + {line: ($n + 1), retired: (.text | startswith("(retired)"))})' "$f"
}

# The live rulings, newest first.
rules_live_json() {
  rules_json | jq -c '
    ([.[].supersedes | select(. != "-")]) as $gone
    | group_by(.topic) | map(max_by(.line))
    | map(select((.id as $i | $gone | index($i) | not) and (.retired | not)))
    | sort_by(-.line)'
}

rules_newid() {
  local have t; have="|$(rules_json | jq -r '[.[].id] | join("|")')|"
  while :; do t="$(printf 'r-%04x' $(( ((RANDOM << 1) ^ RANDOM) & 0xffff )))"; [[ "$have" != *"|$t|"* ]] && break; done
  printf '%s' "$t"
}

# rules_append <ts> <topic> <supersedes|auto> <src> <text>: validates, appends, prints the id.
rules_append() {
  local ts="$1" topic="$2" sup="$3" src="$4" text="$5" id all
  [[ "$topic" =~ ^[a-z0-9][a-z0-9-]*$ ]] || die "topic must be a lowercase slug (a-z, 0-9, -): '$topic'"
  [[ "$src" =~ ^[^[:space:]]+$ ]] || die "src must be one token without spaces: '$src'"
  [[ -n "${text//[[:space:]]/}" ]] || die "a ruling needs text"
  [[ "$text" != *$'\n'* && "$text" != *$'\t'* ]] || die "a ruling is one line (no newlines or tabs)"
  all="$(rules_json)"
  if [[ "$sup" == auto ]]; then
    sup="$(jq -r --arg t "$topic" '[.[] | select(.topic == $t)] | max_by(.line) // {} | .id // "-"' <<<"$all")"
  elif [[ "$sup" != "-" ]]; then
    jq -e --arg s "$sup" 'any(.[]; .id == $s)' <<<"$all" >/dev/null || die "no such ruling: $sup"
  fi
  id="$(rules_newid)"
  printf '%s [%s] topic=%s supersedes=%s src=%s :: %s\n' "$ts" "$id" "$topic" "$sup" "$src" "$text" >>"$(rules_file)"
  printf '%s' "$id"
}

# Rewrite the generated block in the preferences file (append it if missing). Idempotent.
rules_render() {
  local f body; f="$(prefs_file)"
  [[ -f "$f" ]] || cp "$CR_ROOT/templates/commander.md" "$f"
  body="$(rules_live_json | jq -r '
    if length == 0 then "- (none yet)"
    else .[] | "- \(.text) (\(.topic); \(.id), \(.ts[0:10]))" end')"
  RULES_BODY="$body" awk -v b="$RULES_BEGIN" -v e="$RULES_END" '
    function block() { print b; print ENVIRON["RULES_BODY"]; print e; done = 1 }
    index($0, "<!-- chartroom:rulings") == 1 { if (!done) block(); skip = 1; next }
    skip && index($0, e) == 1 { skip = 0; next }
    skip { next }
    { print }
    END {
      if (skip) { print "chartroom: unterminated rulings block" > "/dev/stderr"; exit 3 }
      if (!done) { print ""; print "## Rulings"; print ""; block() }
    }' "$f" >"$f.tmp" && mv "$f.tmp" "$f"
}

# Hand-written top-level bullets outside the generated block, one per line ("- " stripped).
rules_hand_bullets() {
  local f; f="$(prefs_file)"
  [[ -f "$f" ]] || return 0
  awk -v e="$RULES_END" '
    index($0, "<!-- chartroom:rulings") == 1 { skip = 1; next }
    skip { if (index($0, e) == 1) skip = 0; next }
    /^- / && $0 !~ /^- \(none/ { print substr($0, 3) }' "$f"
}

# A tab-separated import map drafted from the hand bullets, for the XO to edit:
#   topic <TAB> supersedes <TAB> date <TAB> text <TAB> original bullet
rules_draft() {
  local b date text topic
  printf '# chartroom rule import map: one row per hand-written bullet in %s\n' "$(prefs_file)"
  printf '# columns (tab-separated): topic, supersedes, date, text, original bullet (do not edit)\n'
  printf '# topic: a slug; rows sharing a topic chain in row order, the last row wins. "keep" leaves\n'
  printf '#   the bullet as hand-written text. supersedes: auto (the topic'"'"'s previous ruling), -,\n'
  printf '#   r-xxxx, or #N (the N-th row of this map, counting rows only).\n'
  while IFS= read -r b; do
    text="$b" date="-"
    if [[ "$text" =~ ^([0-9]{4}-[0-9]{2}-[0-9]{2})(\ \([a-z ]+\))?:[[:space:]]*(.*)$ ]]; then
      date="${BASH_REMATCH[1]}"; text="${BASH_REMATCH[3]}"
    elif [[ "$text" =~ ^(.*[^[:space:]])[[:space:]]*\(([0-9]{4}-[0-9]{2}-[0-9]{2})\)\.?$ ]]; then
      text="${BASH_REMATCH[1]}"; date="${BASH_REMATCH[2]}"
    fi
    topic="$(slugify "$(awk '{print $1, $2, $3}' <<<"${text//[^A-Za-z0-9 ]/ }")")"
    printf '%s\tauto\t%s\t%s\t%s\n' "${topic:-misc}" "$date" "$text" "$b"
  done < <(rules_hand_bullets)
}

# Apply an import map: back up the preferences file, append each row as a ruling
# (src=import), drop the imported bullets from the hand-written text, render the block.
rules_import() {
  local map="$1" apply="$2" f n=0 row topic sup date text orig ts id bak
  local -a ids=() origs=()
  [[ -f "$map" ]] || die "no such map: $map"
  f="$(prefs_file)"
  [[ -f "$f" ]] || die "no preferences file at $f (chartroom init)"
  local -a rows=()
  while IFS= read -r row; do
    [[ -z "$row" || "$row" == \#* ]] && continue
    [[ "$(awk -F'\t' '{print NF}' <<<"$row")" -eq 5 ]] || die "map row needs 5 tab-separated columns: $row"
    rows+=("$row")
  done <"$map"
  for row in "${rows[@]}"; do
    IFS=$'\t' read -r topic sup date text orig <<<"$row"
    n=$((n + 1))
    grep -qxF -- "- $orig" "$f" || die "map row $n: bullet not found in $f: $orig"
    [[ "$date" == "-" || "$date" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] || die "map row $n: date must be YYYY-MM-DD or -: $date"
    [[ "$sup" =~ ^(auto|-|r-[0-9a-f]{4,}|#[0-9]+)$ ]] || die "map row $n: bad supersedes: $sup"
    [[ "$sup" =~ ^#([0-9]+)$ ]] && { (( BASH_REMATCH[1] >= 1 && BASH_REMATCH[1] < n )) || die "map row $n: $sup must name an earlier row"; }
    [[ "$topic" == keep ]] || [[ "$topic" =~ ^[a-z0-9][a-z0-9-]*$ ]] || die "map row $n: topic must be a slug or keep: $topic"
  done
  if [[ "$apply" -ne 1 ]]; then
    n=0
    for row in "${rows[@]}"; do
      IFS=$'\t' read -r topic sup date text orig <<<"$row"; n=$((n + 1))
      if [[ "$topic" == keep ]]; then printf 'keep   #%d %s\n' "$n" "$orig"
      else printf 'rule   #%d topic=%s supersedes=%s date=%s :: %s\n' "$n" "$topic" "$sup" "$date" "$text"; fi
    done
    echo "dry run: nothing written (add --apply to import into $(rules_file) and render $f)"
    return 0
  fi
  mkdir -p "$CR_HOME/records"
  bak="$CR_HOME/records/$(basename "$f" .md)-before-rulings-$(date -u +%Y%m%dT%H%M%SZ).md"
  cp "$f" "$bak"
  echo "backed up $f -> $bak"
  n=0
  for row in "${rows[@]}"; do
    IFS=$'\t' read -r topic sup date text orig <<<"$row"; n=$((n + 1))
    if [[ "$topic" == keep ]]; then ids+=(""); continue; fi
    [[ "$sup" =~ ^#([0-9]+)$ ]] && { sup="${ids[$((BASH_REMATCH[1] - 1))]}"; [[ -n "$sup" ]] || die "map row $n: #${BASH_REMATCH[1]} is a keep row"; }
    if [[ "$date" == "-" ]]; then ts="$(now)"; else ts="${date}T00:00:00Z"; fi
    id="$(rules_append "$ts" "$topic" "$sup" import "$text")"
    ids+=("$id"); origs+=("- $orig")
    printf 'imported %s topic=%s :: %s\n' "$id" "$topic" "$text"
  done
  # Drop the imported bullets (exact lines) from the hand-written text.
  printf '%s\n' "${origs[@]}" >"$f.drop"
  awk 'NR == FNR { drop[$0] = 1; next } !($0 in drop)' "$f.drop" "$f" >"$f.tmp" && mv "$f.tmp" "$f"
  rm -f "$f.drop"
  rules_render
  echo "rendered the live rulings into $f"
}

cmd_rule() {
  local sub="${1:-}"; shift || true
  case "$sub" in
    add) # add --topic T [--supersedes r-x|-] [--src S] <text>
      local topic="" sup=auto src=chat id
      while [[ $# -gt 0 ]]; do
        case "$1" in
          --topic) topic="$2"; shift 2 ;;
          --supersedes) sup="$2"; shift 2 ;;
          --src) src="$2"; shift 2 ;;
          --) shift; break ;;
          -*) die "rule add: unknown flag $1" ;;
          *) break ;;
        esac
      done
      [[ -n "$topic" && $# -ge 1 ]] || die "usage: chartroom rule add --topic <slug> [--supersedes r-xxxx|-] [--src <token>] <text>"
      id="$(rules_append "$(now)" "$topic" "$sup" "$src" "$*")"
      rules_render
      echo "$id"
      ;;
    retire) # retire <r-id> [reason]
      [[ $# -ge 1 ]] || die "usage: chartroom rule retire <r-xxxx> [reason]"
      local rid="$1" topic id; shift
      topic="$(rules_json | jq -r --arg r "$rid" '.[] | select(.id == $r) | .topic')"
      [[ -n "$topic" ]] || die "no such ruling: $rid"
      id="$(rules_append "$(now)" "$topic" "$rid" chat "(retired)${*:+ $*}")"
      rules_render
      echo "$id"
      ;;
    list) # list [--all] [--json]
      local all=0 json=0 a
      for a in "$@"; do case "$a" in --all) all=1 ;; --json) json=1 ;; *) die "rule list: unknown arg $a" ;; esac; done
      local data; if [[ $all -eq 1 ]]; then data="$(rules_json)"; else data="$(rules_live_json)"; fi
      if [[ $json -eq 1 ]]; then jq . <<<"$data"; return 0; fi
      if [[ $all -eq 1 ]]; then
        jq -r '
          ([.[].supersedes | select(. != "-")]) as $gone
          | (group_by(.topic) | map(max_by(.line) | .id)) as $latest
          | .[] | (if (.id as $i | ($gone | index($i)) or ($latest | index($i) | not) or .retired) then "  " else "* " end)
            + "\(.id) \(.ts[0:10]) \(.topic)" + (if .supersedes != "-" then " (supersedes \(.supersedes))" else "" end)
            + " :: \(.text)"' <<<"$data"
      else
        jq -r 'if length == 0 then "no rulings" else .[] | "\(.id) \(.ts[0:10]) \(.topic) :: \(.text)" end' <<<"$data"
      fi
      ;;
    render) rules_render; echo "rendered the live rulings into $(prefs_file)" ;;
    draft) rules_draft ;;
    import) # import <map> [--apply]
      local map="" apply=0 a
      for a in "$@"; do case "$a" in --apply) apply=1 ;; *) map="$a" ;; esac; done
      [[ -n "$map" ]] || die "usage: chartroom rule import <map.tsv> [--apply]"
      rules_import "$map" "$apply"
      ;;
    *) die "usage: chartroom rule add|retire|list|render|draft|import (chartroom help)" ;;
  esac
}
